USE [master]
GO
/****** Object:  Database [EMPRESA]    Script Date: 21/04/2021 10:14:07 p. m. ******/
CREATE DATABASE [EMPRESA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EMPRESA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\EMPRESA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EMPRESA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\EMPRESA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [EMPRESA] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EMPRESA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [EMPRESA] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [EMPRESA] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [EMPRESA] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [EMPRESA] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [EMPRESA] SET ARITHABORT OFF 
GO
ALTER DATABASE [EMPRESA] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [EMPRESA] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [EMPRESA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [EMPRESA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [EMPRESA] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [EMPRESA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [EMPRESA] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [EMPRESA] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [EMPRESA] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [EMPRESA] SET  DISABLE_BROKER 
GO
ALTER DATABASE [EMPRESA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [EMPRESA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [EMPRESA] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [EMPRESA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [EMPRESA] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [EMPRESA] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [EMPRESA] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [EMPRESA] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [EMPRESA] SET  MULTI_USER 
GO
ALTER DATABASE [EMPRESA] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [EMPRESA] SET DB_CHAINING OFF 
GO
ALTER DATABASE [EMPRESA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [EMPRESA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [EMPRESA] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [EMPRESA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [EMPRESA] SET QUERY_STORE = OFF
GO
USE [EMPRESA]
GO
/****** Object:  Table [dbo].[Asiste]    Script Date: 21/04/2021 10:14:08 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Asiste](
	[idAsistencia] [int] IDENTITY(1,1) NOT NULL,
	[fecha] [datetime] NULL,
	[valor] [int] NULL,
	[idTrabajador] [int] NULL,
 CONSTRAINT [pk_relleno] PRIMARY KEY CLUSTERED 
(
	[idAsistencia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Rol]    Script Date: 21/04/2021 10:14:08 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Rol](
	[idrol] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](30) NULL,
	[estatus] [varchar](30) NULL,
 CONSTRAINT [PK_ID] PRIMARY KEY CLUSTERED 
(
	[idrol] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Trabajador]    Script Date: 21/04/2021 10:14:08 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Trabajador](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](30) NULL,
	[apellidos] [varchar](30) NULL,
	[sexo] [varchar](20) NULL,
	[correo] [varchar](30) NULL,
	[idroles] [int] NULL,
	[salario] [float] NULL,
	[fecha] [datetime] NULL,
	[Relleno] [int] NULL,
 CONSTRAINT [PK_IDE] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Asiste] ON 
GO
INSERT [dbo].[Asiste] ([idAsistencia], [fecha], [valor], [idTrabajador]) VALUES (4, CAST(N'2021-04-16T05:47:10.487' AS DateTime), 15, 2)
GO
INSERT [dbo].[Asiste] ([idAsistencia], [fecha], [valor], [idTrabajador]) VALUES (7, CAST(N'2021-04-16T05:58:21.870' AS DateTime), 0, 1)
GO
SET IDENTITY_INSERT [dbo].[Asiste] OFF
GO
SET IDENTITY_INSERT [dbo].[Rol] ON 
GO
INSERT [dbo].[Rol] ([idrol], [nombre], [estatus]) VALUES (1, N'PROGRAMADORES', N'VIGENTE')
GO
INSERT [dbo].[Rol] ([idrol], [nombre], [estatus]) VALUES (2, N'MECANICO', N'VIGENTE')
GO
SET IDENTITY_INSERT [dbo].[Rol] OFF
GO
SET IDENTITY_INSERT [dbo].[Trabajador] ON 
GO
INSERT [dbo].[Trabajador] ([id], [nombre], [apellidos], [sexo], [correo], [idroles], [salario], [fecha], [Relleno]) VALUES (1, N'LEONARDO', N'SAINOS PEREZ', N'MASCULINO', N'leonardosainos@gmail.com', 1, 3000, CAST(N'2021-04-15T01:56:06.470' AS DateTime), NULL)
GO
INSERT [dbo].[Trabajador] ([id], [nombre], [apellidos], [sexo], [correo], [idroles], [salario], [fecha], [Relleno]) VALUES (2, N'LUIS ENRIQUE', N'GRANILLO GAMINO', N'MASCULINO', N'Gamino@gmail.com', 1, 3000, CAST(N'2021-04-15T02:00:16.700' AS DateTime), NULL)
GO
INSERT [dbo].[Trabajador] ([id], [nombre], [apellidos], [sexo], [correo], [idroles], [salario], [fecha], [Relleno]) VALUES (11, N'Alondra ', N'Sanchez', N'Femenino', N'Alondra@gmail.com', 1, 5000, CAST(N'2021-04-16T07:41:02.870' AS DateTime), NULL)
GO
INSERT [dbo].[Trabajador] ([id], [nombre], [apellidos], [sexo], [correo], [idroles], [salario], [fecha], [Relleno]) VALUES (12, N'ArduinoPRUEBAA', N'Dos', N'Femenino', N'ardui@gmail.com', 1, 8000, CAST(N'2021-04-16T17:42:02.870' AS DateTime), NULL)
GO
SET IDENTITY_INSERT [dbo].[Trabajador] OFF
GO
ALTER TABLE [dbo].[Asiste] ADD  DEFAULT (getdate()) FOR [fecha]
GO
ALTER TABLE [dbo].[Trabajador] ADD  DEFAULT (getdate()) FOR [fecha]
GO
ALTER TABLE [dbo].[Asiste]  WITH CHECK ADD  CONSTRAINT [fk_prueba] FOREIGN KEY([idTrabajador])
REFERENCES [dbo].[Trabajador] ([id])
GO
ALTER TABLE [dbo].[Asiste] CHECK CONSTRAINT [fk_prueba]
GO
ALTER TABLE [dbo].[Trabajador]  WITH CHECK ADD  CONSTRAINT [FK_ROL] FOREIGN KEY([idroles])
REFERENCES [dbo].[Rol] ([idrol])
GO
ALTER TABLE [dbo].[Trabajador] CHECK CONSTRAINT [FK_ROL]
GO
USE [master]
GO
ALTER DATABASE [EMPRESA] SET  READ_WRITE 
GO
